indent-width = 4
line-length  = 120
extend-exclude = [".venv"]
src = ["src"]
force-exclude = true

[format]
docstring-code-format = true
indent-style = "space"
line-ending = "lf"
quote-style = "double"
skip-magic-trailing-comma = true

[lint]
dummy-variable-rgx = "^_$"
select = [
    "F",    # Pyflakes
    "I",    # isort
    "E",    # pycodestyle
    "W",    # pycodestyle
    "D",    # pydocstyle
    "N",    # pep8-naming
    "UP",   # pyupgrade
    "C90",  # mccabe
    "S",    # flake8-bandit
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "INP",  # flake8-no-pep420
    "T20",  # flake8-print
    "Q",    # flake8-quotes
    "G",    # flake8-logging-format
    "PTH",  # flake8-use-pathlib
    "SIM",  # flake8-simplify
    "FURB", # refurb
    "RUF",  # Ruff-specific rules
    "PGH",  # pygrep-hooks
]
ignore = [
    "W191",
    "E111",
    "E114",
    "E117",
    "D206",
    "D300",
    "Q000",
    "Q001",
    "Q002",
    "Q003",
    "COM812",
    "COM819",
    "ISC001",
    "ISC002",
]

[lint.pydocstyle]
convention = "google"

[lint.mccabe]
max-complexity = 10
