extend-exclude = [".venv"]
force-exclude  = true
indent-width   = 4
line-length    = 120
src            = ["src"]

[format]
    docstring-code-format     = true
    indent-style              = "space"
    line-ending               = "lf"
    quote-style               = "double"
    skip-magic-trailing-comma = true

[lint]
    dummy-variable-rgx = "^_$"
    ignore = ["COM812", "COM819", "D206", "D300", "E111", "E114", "E117", "ISC001", "ISC002", "Q000", "Q001", "Q002", "Q003", "W191"]
    select = [
        "B",    # flake8-bugbear
        "C4",   # flake8-comprehensions
        "C90",  # mccabe
        "D",    # pydocstyle
        "E",    # pycodestyle
        "F",    # Pyflakes
        "FURB", # refurb
        "G",    # flake8-logging-format
        "I",    # isort
        "INP",  # flake8-no-pep420
        "N",    # pep8-naming
        "PGH",  # pygrep-hooks
        "PTH",  # flake8-use-pathlib
        "Q",    # flake8-quotes
        "RUF",  # Ruff-specific rules
        "S",    # flake8-bandit
        "SIM",  # flake8-simplify
        "T20",  # flake8-print
        "UP",   # pyupgrade
        "W",    # pycodestyle
    ]

[lint.pydocstyle]
    convention = "google"

[lint.mccabe]
    max-complexity = 10
